### ISSUE TITLE
Consider including multiple origin names in TokenChallenge

### ISSUE THREAD

**Issue by chris-wood** [ietf-wg-privacypass/base-drafts#108]
From Ted Hardie in Vienna.

**Comment by tfpauly** [comment]
We should also clarify more explicitly how the client uses the origin name field for validating the context it is in.

**Comment by tfpauly** [comment]
Leaning towards allowing the `origin_name` being able to be a list of hostnames, with comma separation.

**Comment by smhendrickson** [comment]
+1 to csv. We think this keeps the client impl's simple while allowing for the added flexibility of origin sets.

**Comment by richsalz** [comment]
Might also have to say something about ignoring whitespace `a,b` vs `a, b` and then maybe just whitespace is the separator?

**Comment by chris-wood** [comment]
While I can understand the appeal, I'm not yet convinced we should do this until we have a use case and have thought through the possible privacy impacts.
