### ISSUE TITLE
Look at greasing Client / Origin interactions

### ISSUE THREAD

**Issue by tfpauly** [ietf-wg-privacypass/base-drafts#113]
Origins can issue challenges for greased token types, etc, to ensure client can handle new types in the future.

**Comment by chris-wood** [comment]
One type of greasing might be adding random authentication credentials to the `Authorization` header, e.g., `Authorization: PrivacyToken foo=bar token=blah bar=baz`.

**Comment by tfpauly** [comment]
We should recommend servers to send greased token types + parameters, as well as clients to send greased credentials.
