### ISSUE TITLE
Don't require padding for base64url?

### ISSUE THREAD

**Issue by punkeel** [ietf-wg-privacypass/base-drafts#117]
I would like to challenge the following snippet in the RFC, especially the use of the word **MUST**.
> "challenge", which contains a base64url-encoded {{!RFC4648}} TokenChallenge value. **Since the length of the challenge is not fixed, the base64url data MUST include padding.**

Base 64 decoding does not require the padding to get the *exact* encoded value, bit-for-bit.

From what I understand, issues arise when it's impossible to know the length of the encoded base64 payload, due to lack of delimiters. eg, if we encode `hello` and `world`, then concat them (without padding), this gives us:
`aGVsbG8=` + `d29ybGQ=` == `aGVsbG8d29ybGQ` ==> `hello.ÛÜ..`

When the base64 length is fully known (thanks to delimiters like space or line breaks), this is a non-issue.

May I recommend that clients instead **MUST support** base64url encoding with and without padding?

**Comment by chris-wood** [comment]
Thanks for filing @punkeel! There's a couple reasons why we went with padding. First, padding seems to be the default encoding for most [many](https://docs.rs/base64/latest/base64/index.html) [base64](https://pkg.go.dev/encoding/base64) [implementations](https://source.chromium.org/chromium/chromium/src/+/main:base/base64url.h). Second, as you point out, no padding is an issue without a known length, so this would require us to specify that length in order to help clients parse things correctly. That pushes complexity into the protocol. Putting these together, allowing unpadded base64 would just force all clients to implement a thing that's not really needed while also making the protocol more complex, so it didn't seem worth the flexibility.

**Comment by tfpauly** [comment]
There's also a desire amongst the authors to keep the supported cases be stricter and more limited to avoid interop problems.

The question I have is who benefits by allowing the specification to be loose here in allowing both forms in both directions?

**Comment by punkeel** [comment]
The demo sitekey provided by Fastly ([here](https://www.fastly.com/blog/private-access-tokens-stepping-into-the-privacy-respecting-captcha-less)) doesn't include padding symbols. 

`MIICUjA9BgkqhkiG9w0BAQowMKANMAsGCWCGSAFlAwQCAqEaMBgGCSqGSIb3DQEBCDALBglghkgBZQMEAgKiAwIBMAOCAg8AMIICCgKCAgEAubzND7lvK-u5aIFHSt_NHIzsUFuHCiwVm88kvUvbvJbjj4be_IdNwpfdfXz-vq6NeEwlKEDLtD9oMVop_kEf5HEBkiipBrcn10h17XvYPuc6lA7Z4Y8IjvSjLVydXmcabmslwreMysD1ZINjzadjlJxiIKWCeS_3OJ4dxMTirt8HMUl8cRQafTjSOBJIZNtoNiT5rr5_5SYfEQW8v25RZcitkL0Lrg1mkSutRR00EE3zMelQBGR0sf8jDgBRiPQ1-sSgaIicIciZ2ysiPdkQZBIDpIFnvqed4yKY9gZCn-ASztoe1JhJvzWUwO7Nyz1Mb6pxAV0aQNfb0rDMTPNtyF4z7kgtFcsr5SXiJUa13bm0G2QvEdhl177poghh2RDaT5tcEmiRRvdQWBTeVgFyjrX3-29TZCT4z8VyvDxPPIUIi2rN8-9lN6mmsF0KhlyKe4jUuDwK7dc6Q0gZyjKiE3n-ygErrlbOYU16MGQiJQRV6Z8j38OSD4Lf5-SzsgkAa6Zbv95Zf8TZRS-fuagiXGZcmfdO9zXkuNlRlGguEUpx520SANRciPIBZxFBDXga6kcT9Hfha0n97Mhq57kFRe2Cox7qpq79x9TjUvHOZkWMSv2KmZpoF0wbI2NvlZngbW6Z1hC-X4C3evilX7O498r45Ct7PNjq11Qjso82DwMCAwEAAQ`

Length is 798, and `798 % 4 = 2`. It should end with `==`.

(Sorry for not coming back to this earlier, no strong opinions – it's almost a personal preference at this point)

**Comment by jfoote** [comment]
The lack of padding was an oversight and has been fixed FWIW. 

```
MIICUjA9BgkqhkiG9w0BAQowMKANMAsGCWCGSAFlAwQCAqEaMBgGCSqGSIb3DQEBCDALBglghkgBZQMEAgKiAwIBMAOCAg8AMIICCgKCAgEAubzND7lvK-u5aIFHSt_NHIzsUFuHCiwVm88kvUvbvJbjj4be_IdNwpfdfXz-vq6NeEwlKEDLtD9oMVop_kEf5HEBkiipBrcn10h17XvYPuc6lA7Z4Y8IjvSjLVydXmcabmslwreMysD1ZINjzadjlJxiIKWCeS_3OJ4dxMTirt8HMUl8cRQafTjSOBJIZNtoNiT5rr5_5SYfEQW8v25RZcitkL0Lrg1mkSutRR00EE3zMelQBGR0sf8jDgBRiPQ1-sSgaIicIciZ2ysiPdkQZBIDpIFnvqed4yKY9gZCn-ASztoe1JhJvzWUwO7Nyz1Mb6pxAV0aQNfb0rDMTPNtyF4z7kgtFcsr5SXiJUa13bm0G2QvEdhl177poghh2RDaT5tcEmiRRvdQWBTeVgFyjrX3-29TZCT4z8VyvDxPPIUIi2rN8-9lN6mmsF0KhlyKe4jUuDwK7dc6Q0gZyjKiE3n-ygErrlbOYU16MGQiJQRV6Z8j38OSD4Lf5-SzsgkAa6Zbv95Zf8TZRS-fuagiXGZcmfdO9zXkuNlRlGguEUpx520SANRciPIBZxFBDXga6kcT9Hfha0n97Mhq57kFRe2Cox7qpq79x9TjUvHOZkWMSv2KmZpoF0wbI2NvlZngbW6Z1hC-X4C3evilX7O498r45Ct7PNjq11Qjso82DwMCAwEAAQ==
```

**Comment by tfpauly** [comment]
Based on this, I think we'll stick with requiring padding. Thanks!
