### ISSUE TITLE
Blind RSA identifier 

### ISSUE THREAD

**Issue by chris-wood** [ietf-wg-privacypass/base-drafts#120]
The SPKI format is currently unspecified, and as there are multiple ways to encode an RSA public key (and hash algorithm), this makes interop somewhat difficult. Moreover, the SPKI can encode any number of RSA public key sizes, in contrast to elliptic curves wherein the "suite" typically defines the key size. In the name of simplicity, I'd propose that we have the identifier fully specify everything one needs to use the algorithm, including key size, hash algorithm, and encoding format.

**Comment by tfpauly** [comment]
Clarified that this would mean that each token type fully specifies the algorithms and sizes it uses. I support this.
