### ISSUE TITLE
Question on issuer public key retrieval 

### ISSUE THREAD

**Issue by mirjak** [ietf-wg-privacypass/base-drafts#124]
draft-ietf-privacypass-architecture says in section 3.2:

> The mechanism by which clients obtain the Issuer public key is not specified.

Is that correct? Isn't the 'token-key' in draft-ietf-privacypass-auth-scheme providing the pub key? Or do I misunderstand something here?

**Comment by chris-wood** [comment]
Oops, yep, good catch! We'll fix this.
