### ISSUE TITLE
Feedback on compromised attestations

### ISSUE THREAD

**Issue by philippp** [ietf-wg-privacypass/base-drafts#141]
Over a long enough timeline, attestations will be broken - through willful post-boot compromise, malware, or other means. Services that depend on attestations (consumers of access tokens) will observe clients that appear to pass attestation, but engage in behavior that indicates that the device is compromised (e.g. trigger thousands of interactions per second).

As it stands, the service consuming access tokens is not able to provide feedback that these attestations appear to be false negatives, and should be re-examined by the attester. Even if this feedback were to be provided out of band, it will be challenging for the attester to identify which devices are compromised and diagnose the nature of the compromise.

I do not anticipate that this will become a pressing issue until the initial attestations are compromised, but it may be helpful to plan ahead for this scenario.

**Comment by chris-wood** [comment]
Thanks, @philippp! This seems like something we ought to discuss in the architecture document.
