### ISSUE TITLE
Preventing reliance on privacy pass

### ISSUE THREAD

**Issue by tfpauly** [ietf-wg-privacypass/base-drafts#146]
From IETF 114 discussion:

For the general captcha use cases, we don't want websites to rely on privacy pass always working, to preventing locking out other clients.

We should likely have discussion in the architecture document to suggest approaches to make sure servers can't rely on this for generic clients (like browsers). Randomly not responding with tokens, other client-side heuristics.

**Comment by chris-wood** [comment]
I would put this in the auth-scheme document, where we already discuss user experience things. I'll propose some text that we can wordsmith.
