### ISSUE TITLE
Architecture: One protocol or two?

### ISSUE THREAD

**Issue by tfpauly** [ietf-wg-privacypass/base-drafts#153]
The intro says this:

> Privacy Pass is a protocol for authorization based on anonymous-credential authentication mechanisms. 

It also says this:

> At a high level, Privacy Pass is composed of two protocols: issuance and redemption.

It may be clearer to not call Privacy Pass both "a protocol" and "two protocols". Either we call issuance and redemption "sub-protocols", or we call the main thing "a mechanism", "an architecture", or "a set of protocols". I kinda lean towards the last option.

**Comment by ekinnear** [comment]
Had the same thought while reading the introduction, in the abstract it is referred to as an `architectural framework`, so perhaps just:
> Privacy Pass is a framework for authorization based on anonymous-credential authentication mechanisms.

or just a "set of protocols" would work nicely too.
