### ISSUE TITLE
Cross-origin MUST NOT

### ISSUE THREAD

**Issue by tfpauly** [ietf-wg-privacypass/base-drafts#155]
> If tokens protected with resources are unique to a single Origin, then said Origin MUST NOT admit cross-origin tokens for authorization.

I'm not sure I follow what this is saying. Does it intend to say "resources protected with tokens"? It also seems like a hard thing to enforce normatively without being more clear.

**Comment by chris-wood** [comment]
Removing this sentence altogether seems best. We already say that origins bear risk in accepting cross-origin tokens issued by interactions with other origins.
