### ISSUE TITLE
Architecture nit: RFC 2119 keywords in section 3

### ISSUE THREAD

**Issue by ekinnear** [ietf-wg-privacypass/base-drafts#160]
Nit: Section 3 contains quite a few places where 2119 keywords are used uncapitalized, which can be fine, but there are enough of them that it might be worth doing a quick pass to make sure that's all intentional. 

For example: 

> The fundamental requirement for key management and discovery is that Issuers must be unable to target specific clients with unique keys without detection.

which was proceeded by: 

> To facilitate issuance, the Issuer MUST hold an Issuance key pair at any given time. The Issuer public key MUST be made available to all Clients in such a way that key rotations and other updates are publicly visible. 

All three of these requirements seem rather equally important, and while normative text doesn't need to use capitalized 2119 keywords, I'm assuming there wasn't intentionally any significance to the difference in their use between those paragraphs.

**Comment by chris-wood** [comment]
I don't think they're really enforceable, so moving away from 2119 language seems best here.
