### ISSUE TITLE
Architecture: Key rotation recommendations don't depend on number and frequency of client interactions?

### ISSUE THREAD

**Issue by ekinnear** [ietf-wg-privacypass/base-drafts#162]
Section 5.2 states:
> With a large number of Clients, a minimum of one week gives a large enough
window for Clients to participate in the issuance protocol and thus enjoy the
anonymity guarantees of being part of a larger group. A maximum of
12 weeks limits the damage caused by a key compromise. If an Issuer
realizes that a key compromise has occurred then the Issuer should
generate a new key and make it available to Clients. If possible, it should
invoke any revocation procedures that may apply for the old key.

Is this 1-12 week recommendation really universally applicable, or should an implementor/deployer take into account the number and frequency of client interactions? It seems like the real goal is the _size_ of the anonymity set, not the number of days (modulo risk of key compromise). For example, if there's a system that only has 10 clients a week, would it make sense to use a longer value?

**Comment by chris-wood** [comment]
Great catch. We should just remove this recommendation and describe the tradeoff more clearly (which is somewhat done).
