### ISSUE TITLE
Arch: s.5.3: Meaning of "distribution of Issuer trust"

### ISSUE THREAD

**Issue by cjpatton** [ietf-wg-privacypass/base-drafts#169]
I'm not sure how to interpret the following:

> If the distribution of Issuer trust is anything close to a uniform distribution, then this is likely to uniquely identify any Client amongst all other Internet users. Assuming a uniform distribution is clearly the worst-case scenario, and unlikely to be accurate, but it provides a stark warning against allowing too many Issuers at any one time.

What is meant the "distribution of Issuer trust" here?

Relatedly, can you explain the math here:

> We propose that allowing no more than 4 Issuers at any one time is highly preferable (leading to a maximum of 64 possible user segregations).

My understanding is that the set of users can be partitioned into 2^4 = 16 different sets (not 64). More than likely I'm missing something obvious. Either way, this seems like a reasonably conservative recommendation. (It's hard for me to imagine more than a handful of Issuers being active in a deployment.)

**Comment by chris-wood** [comment]
Yeah, this was really unclear, mostly because it was left over from a prior version of the document. I tried to consolidate and clarify the text in this section (and its subsections) to improve the situation. Please have a look at #178 for the proposed change!
