### ISSUE TITLE
Arch S3.2: Unconditional input secrecy

### ISSUE THREAD

**Issue by nikitaborisov** [ietf-wg-privacypass/base-drafts#179]
Is _unconditional_ input secrecy meant to mean similar to unconditionally hiding? If so, this probably deserves more explanation and  justification in the architecture document as a requirement; otherwise, a different term should probably be used.

**Comment by chris-wood** [comment]
To my knowledge unconditional input secrecy is the standard term here. What do you think should be added to resolve this issue?

**Comment by nikitaborisov** [comment]
I guess my main question is why is _unconditional_ secrecy a requirement here?

**Comment by chris-wood** [comment]
Because we don't want the server to learn anything about the client's private input regardless of its computational power.

**Comment by nikitaborisov** [comment]
1. I think this should be spelled out explicitly; i.e., say explicitly that the client's private input should remain private even if some of the cryptographic hardness assumptions underlying the protocol become falsified. 
2. I wonder if this would be a good place to use a SHOULD vs a MUST. I can see how unconditional secrecy is a desirable property, but, e.g., TLS doesn't have it for obvious reasons.

**Comment by chris-wood** [comment]
I sent a PR for (1). I don't think we should relax (2). Future versions of the architecture can update this requirement to relax as desired.
