### ISSUE TITLE
Arch: s3.1 transitive trust in attester—clarification

### ISSUE THREAD

**Issue by nikitaborisov** [ietf-wg-privacypass/base-drafts#187]
I found this sentence hard to interpret:

> The selected Issuer transitively determines what types of attestation the Origin is willing to accept.

both because of the use "transitive" and because, AIUI, the Origin does not directly accept attestations at all. I tried to be a bit more explicit in this phrasing:

> Each Issuer, in turn, determine which Attesters it is willing to accept in the issuance protocol. This means that if an Origin origin.example accepts tokens issued by Issuer issuer.example, and that Issuer in turn accepts attestations from Attesters attester1.example and attester2.example, then a client may use either of the Attesters for accessing origin.example. However, origin.example does not explicitly specify and indeed need not know the identities of the Attesters

**Comment by chris-wood** [comment]
Good clarification! Please check out the linked PR where I applied a variant of your suggested text.
