### ISSUE TITLE
Arch: joint Attester and Origin

### ISSUE THREAD

**Issue by nikitaborisov** [ietf-wg-privacypass/base-drafts#189]
This seems to me like a useful deployment option in cases where the Origin performs its own account management but wants to have it be unlinkable from account use. Consider, e.g., a newspaper that is subscription only, where the newspaper wants to make sure that only subscribers access articles, but it does not want to be able to track which subscribers read which articles. 

This is different significantly the joint Origin, Issuer, and Attester since you _can_ use authentication methods that utilize the client's identity. I'm not sure if this is a lot different from the case where all three of Attester, Origin, Issuer are distinct from a security perspective, except that obviously a joint Attester and Origin cannot be assumed to not collude with each other.

**Comment by chris-wood** [comment]
In this example, why would the joint Attester and Origin outsource token issuance to a third party? This seems like a use case for the shared Attester, Issuer, and Origin model to me. Thoughts?

**Comment by chris-wood** [comment]
Closing based on the above. We can re-open and add this model if more people think it'd be useful.
