### ISSUE TITLE
Slightly more specific content types?

### ISSUE THREAD

**Issue by quartzjer** [ietf-wg-privacypass/base-drafts#199]
I see in the current draft that they register `message/token-request` and `message/token-response`.

Since "token" is a very broad term, I'm wondering if something slightly more specific to Privacy Pass such as `message/privacy-token-request` and `message/privacy-token-response` might be reasonable?

**Comment by tfpauly** [comment]
If we make it more specific, it should be "private" instead of "privacy", to be "private-token" and align with the auth scheme.

There's a fair amount of deployment on these types today, so this would be a relatively large change, or servers would need to tolerate both versions.

**Comment by tfpauly** [comment]
Cool, that would work. @chris-wood want to make the proposed update?

**Comment by chris-wood** [comment]
Will do!

**Comment by chris-wood** [comment]
@tfpauly PR's up!
