### ISSUE TITLE
Effective mechanism for identifying malicious servers

### ISSUE THREAD

**Issue by alxdavids** [ietf-wg-privacypass/base-drafts#2]
Need to provide recommendations for section {{recs-srvr}} in the pp-architecture draft. It seems to me that it is easy for individual clients to identify and react to servers that seem to be acting maliciously. For example, the client can monitor and reject key material from servers where the configuration was last modified very recently and how often the rotations seem to be occurring. However, I'm not exactly sure what the reporting mechanism should be to alert other clients to this behavior.

**Comment by claucece** [comment]
Mmm.. this is quite interesting. 

Something that can be imposed to the server is to have a window of time in which rotations can't happen. I was thinking on something like this:

* When a server updates their configuration (every 1 to 12 weeks as recommended), it does not immediately use this new configuration; but rather continues using the old one for shorter time frame (less than the 1 to 12 weeks, referred now as `t`), and makes clients aware of a new configuration that is coming. During `t`, the server cannot generate a new configuration. When `t` passes, the server starts using the new configuration (which clients can be sort of aware already). 

This will make hard for a server to update in quick intervals, and that new configurations are not immediately used.

I'm not sure about how much this will work, and I'll have to think more about it ;)

Something, that I don't know if is mentioned in the drafts is defining what happens is a server is rendered unavailable, in some sort of DoS. Maybe nothing can be done in that case...

**Comment by phyo734** [comment]
0x170DBdd337bA421fED5498279a61db29B66aB37d

**Comment by chris-wood** [comment]
(Deleted spam comment)

**Comment by chris-wood** [comment]
This has sort of been overcome by events. The architecture draft now states that clients can apply consistency checks, referencing another draft for ways that can be addressed. Closing as a result.
