### ISSUE TITLE
Guidance on issuer selection

### ISSUE THREAD

**Issue by chris-wood** [ietf-wg-privacypass/base-drafts#20]
(This might be done already, but just in case...)

We should probably provide guidance on how clients should pick issuers. For example, if a client is presented with a choice of two issuers, what does it do? Pick the same one and use it "all the time," pick one at random, or something else?

**Comment by alxdavids** [comment]
I've added some advice on what Issuer features a Client should bear in mind when deciding which to choose. Do you think we still need advice on what to do if presented two at once? I imagine that the Client's should have hard-coded preferences.

**Comment by alxdavids** [comment]
@chris-wood Any opinions on best way forward here, happy to tackle this as it doesn't seem like a huge problem.

**Comment by chris-wood** [comment]
This might be something we punt on, as it's sort of akin to key discovery. I'll close this as such, given that you already have some text in the draft for it now.
