### ISSUE TITLE
Auth scheme: GREASEing

### ISSUE THREAD

**Issue by LPardue** [ietf-wg-privacypass/base-drafts#217]
The spec recommends some greasing in Section 3

> To mitigate the risk of deployments becoming dependent on tokens, clients and servers SHOULD grease their behavior unless explicitly configured not to. In particular, clients SHOULD ignore token challenges with some non-zero probability. Likewise, origins SHOULD randomly choose to not challenge clients for tokens with some non-zero probability. Moreover, origins SHOULD include random token types in token challenges with some non-zero probability.

In section 5.2, several token types are reserved as greased values. 

Is the expectation really that origins pick "random" token types, or with non-zero global probability across clients, randomly pick from the set of reserved token types?

**Comment by dvorak42** [comment]
This should probably read from the list of reserved GREASE values, rather than random token types (the latter can cause interop issues).

**Comment by LPardue** [comment]
Yeah, that sounds good,
