### ISSUE TITLE
Proto: why are you shouting?

### ISSUE THREAD

**Issue by LPardue** [ietf-wg-privacypass/base-drafts#225]
> This document DOES NOT cover the architectural framework required for running and maintaining the Privacy Pass protocol in the Internet setting. In addition, it DOES NOT cover the choices that are necessary for ensuring that client privacy leaks do not occur. Both of these considerations are covered in [[I-D.ietf-privacypass-architecture](https://www.ietf.org/archive/id/draft-ietf-privacypass-protocol-06.html#I-D.ietf-privacypass-architecture)].

Is there a more polite way to phrase this disclaimer?

**Comment by dvorak42** [comment]
This follows RFC 2119 (https://www.rfc-editor.org/rfc/rfc2119) and RFC 8174 linked from terminology where these are reserved phrases with specific meaning in IETF specifications and documents.

Though technically these should probably be "SHOULD NOT" and "SHALL NOT" to be in line with the RFC terms.

**Comment by LPardue** [comment]
What requirements are being defined in the quoted text though? Is it simply a statement of fact like "this document doesn't cover architectural stuff" or is it "implementations of the issuance protocol SHOULD account for considerations related to operations and privacy described in the architecture document"?
