### ISSUE TITLE
Proto: is the Internet important?

### ISSUE THREAD

**Issue by LPardue** [ietf-wg-privacypass/base-drafts#226]
There are two cases where the term `Internet` seems to be used with importance.

> This document DOES NOT cover the architectural framework required for running and maintaining the Privacy Pass protocol in the Internet setting.

> Client: An entity that provides authorization tokens to services across the Internet, in return for authorization.

I suspect that the Internet isn't actually that important in the context / scope of this protocol document, especially since the architecture document doesn't mention it.

**Comment by chris-wood** [comment]
Yep, good catch. It's not.
