### ISSUE TITLE
Proto: what URI or URL specs are you depending on, and what is the scope of allowed URI contents

### ISSUE THREAD

**Issue by LPardue** [ietf-wg-privacypass/base-drafts#229]
Issuers MUST provide a configuration `Issuer Request URI` , so what spec should they be referring to in order to ensure that this URI is well formed? I started wondering about how percent-encoding might apply, and that got me on to thinking whether you really want to support something like

`"issuer-request-uri": "https://john.doe@www.example.com:123/forum/questions/?tag=networking&order=newest#top",

**Comment by chris-wood** [comment]
Unless I'm missing something, I don't think there should be any constraints on how the URI is constructed. We should say something about how it's encoded, though. That's a good point.
