### ISSUE TITLE
Proto: Token Type

### ISSUE THREAD

**Issue by LPardue** [ietf-wg-privacypass/base-drafts#231]
table 2 says:

> 

token-type | Integer value of the Token Type, as defined in Section 8.1, as a JSON number
-- | --

and Section 8.1 says:

> This document updates the "Token Type" Registry with the following values.

What is the Token Type registry and what are the constraints on values in the registry? It's implied that values should be integers but JSON numbers are quite flexible, so would it be valid for me to register e.g. a negative integer. If the "Token Type" registry already exists, I'm not able to find it and a link would be useful. If it doesn't exist and this document wishes to create it, then more work is needed to establish that registry and it's procedures.

**Comment by chris-wood** [comment]
We're missing a link to the HTTP auth document, where the registry is defined. Good catch!
