### ISSUE TITLE
Auth: interaction model

### ISSUE THREAD

**Issue by mnot** [ietf-wg-privacypass/base-drafts#242]
it's not crystal-clear what the interaction model for this auth scheme is.

In many auth schemes, the credential is repeated on each request, to keep the protocol stateless, and to prove the client's identity. 

However, that doesn't seem to be desireable here -- not only would it make all of those responses uncacheable, it would (AIUI) 'spend' a lot of private tokens. OTOH, the 'realm' parameter is explicitly supported (albiet without much detail), which implies the opposite. 

I _think_ the preferred interaction model is that a token is only spent upon an explicit challenge from the server, but it was difficult to discern this from the documentation.

Either way, it'd be good to clarify this.

**Comment by tfpauly** [comment]
Correct, the client shouldn't spend a token multiple times, and shouldn't keep including the credential on future requests.

We could drop the realm text, but I think allowing it as a MAY does leave open use cases that might want to segment up different use cases of tokens.

**Comment by chris-wood** [comment]
Yeah, unless there's a reason to omitting it, I think keeping the MAY for the realm is fine. I tried to get a sense for how clients are intended to use other auth schemes from RFC 9110, but it wasn't clear to me. @tfpauly, do you know of other auth scheme specifications that make the interaction model more clear?
