### ISSUE TITLE
Protocol document should explain (optional) attester behavior

### ISSUE THREAD

**Issue by tfpauly** [ietf-wg-privacypass/base-drafts#267]
Split attesters and issuers are not required for the basic issuance protocol, but we should explain (in a sentence or so) that if you are using a split attester, the client sends the request to the attester, and the attester forwards the request to the issuer if it accepts the client.

**Comment by donivatamazondotcom** [comment]
For better clarity and consistency, I recommend adding a sequence diagram depicting this model considering the sequence diagrams that outline other models.

**Comment by chris-wood** [comment]
Agreed. This would be a good thing to include. I'll take this and add it.

**Comment by plisiecki1** [comment]
In a split attester/issuer scenario, the issuer needs to authenticate the attester in some way (e.g., TLS client cert).

In a combined attester/issuer scenario, the actual protocol might be something proprietary (or covered by an as-yet-unwritten spec) that extends the base issuance protocol, e.g., adding an attestation header, user login cookie, or adding extra challenge/response rounds to confirm identity.

If these issues are "in scope" then they should be defined here. If they are "out of scope" then it would be helpful context to reader to describe what is expected to be handled by a proprietary extension.

**Comment by chris-wood** [comment]
@plisiecki1 we discuss these things in the architecture document where deployment models are discussed. But we should mention the impact that different deployment models have on the basic issuance protocol in the -protocol spec.
