### ISSUE TITLE
Define Verifier?

### ISSUE THREAD

**Issue by ShivanKaul** [ietf-wg-privacypass/base-drafts#269]
[Section 5.4](https://datatracker.ietf.org/doc/html/draft-ietf-privacypass-protocol#section-5-4) discusses verification, but doesn't define the role of a Verifier. I'm guessing this is because the definition is trivial (Verifiers... verify) but is the intention for the Origin to always be the Verifier? Or could that be delegated? We could have the following addition to Terminology:

>- Verifier: Verifiers verify that a particular Token is valid using either the Issuer's Private Key and Public Key (for the private verification variant) or only the Issuer's Public Key (for the public verification variant). This is typically the same as the Origin.

**Comment by chris-wood** [comment]
This was fixed to avoid the use of the term "Verifier."
