### ISSUE TITLE
Define Nk

### ISSUE THREAD

**Issue by ShivanKaul** [ietf-wg-privacypass/base-drafts#270]
[Section 6.1](https://datatracker.ietf.org/doc/html/draft-ietf-privacypass-protocol#section-6-1-7-3) doesn't define `Nk`. The preceding text to the example says that Nk is 512, but AFAICT the value of Nk is not relevant to the example.

**Comment by plisiecki1** [comment]
Section 8.2 defines Nk=256 for type 0x0002. Section 6.1 should still apply for any value Nk if another type is added for a different size key. My two suggestions would be: (1) mention in Section 6.1 that Nk is fixed according to the token type definition and (2) use Nk=256 for the example so it matches the only currently defined blind token type (0x0002).
