### ISSUE TITLE
Parentheses for JSON citations

### ISSUE THREAD

**Issue by martinthomson** [ietf-wg-privacypass/base-drafts#272]
> The Issuer parameters can be obtained from an Issuer via a directory object, which is a JSON object [[RFC8259](https://datatracker.ietf.org/doc/html/draft-ietf-privacypass-protocol-07#RFC8259)], [Section 4](https://rfc-editor.org/rfc/rfc8259#section-4) whose values are other JSON values [[RFC8259](https://datatracker.ietf.org/doc/html/draft-ietf-privacypass-protocol-07#RFC8259)], [Section 3](https://rfc-editor.org/rfc/rfc8259#section-3) for the parameters.

Might be better as:

> The Issuer parameters can be obtained from an Issuer via a directory object, which is a JSON object ([[RFC8259](https://datatracker.ietf.org/doc/html/draft-ietf-privacypass-protocol-07#RFC8259)], [Section 4](https://rfc-editor.org/rfc/rfc8259#section-4)) whose values are other JSON values ([[RFC8259](https://datatracker.ietf.org/doc/html/draft-ietf-privacypass-protocol-07#RFC8259)], [Section 3](https://rfc-editor.org/rfc/rfc8259#section-3)) for the parameters.

See also #271.

**Comment by chris-wood** [comment]
This was fixed in @ShivanKaul's PR. Thanks, @ShivanKaul!
