### ISSUE TITLE
Partitioning of users

### ISSUE THREAD

**Issue by martinthomson** [ietf-wg-privacypass/base-drafts#278]
There are claims in [Section 7 of the protocol](https://www.ietf.org/archive/id/draft-ietf-privacypass-protocol-07.html#section-7) about the value of truncating the issuer's key identifier that I don't think hold outside of having some sort of consistency.

Let's say that I - your hypothetical attacker - want to partition users into 257 groups.  I give the first 255 groups a unique key for which the last byte of `token_key_id = SHA256(concat(0x0001, SerializeElement(pkI)))` is distinct.  For the last two users, I can generate two keys that map to the remaining byte value.

For the private validation setting, I can issue clients with unique values for `pkI` and tokens that match.  When validating the token, that's me (the attacker) again, so I can validate against both keys.  The complexity of my operation has doubled, but it's a linear search and maybe I can keep the numbers down to manage overall costs.

In a public validation setting, I have to ensure that any entity that might validate the tokens also gets a matching value for `pkI`, or that they are complicit in the attack and so are willing to do the extra work.  Generally, this is only the client still, so this is probably achievable, though there is a risk of an independent audit catching this.

Going from 8 bits to 9 bits of partition space doubles the work for any validator, and each additional bit doubles again.  That might be OK, but the claims would appear to be somewhat more absolute than this result implies:

> Since the key ID is truncated to a single byte, an Issuer can partition the set of Clients into at most 256 different anonymity sets.

Also, even this isn't a great outcome either.  256 is pretty large, and the partitioning allocation (again, absent consistency) is under attacker control.

**Comment by chris-wood** [comment]
Good point. The bound was written under the assumption that the attacker does no work to tag clients, but that bound goes up provided it's willing and able to keep more keys around. I think we ought to just drop the explicit bound check here and rewrite things to suggest that tagging is "not feasible at scale" (or whatever), which is something I'm comfortable with saying. Absent consistency, that's the best sort of guarantee I think we'll get. 

Beyond this editorial change, we could truncate the key identifier even further to make this tradeoff involve more work for the attacker. Going from 8 bits down to n \in {2,3,4} bits seems pretty reasonable to me, giving us a window of 2^n keys.

**Comment by plisiecki1** [comment]
2^4 seems reasonable to me.  2^2 is too tight for managing rotations and leaves very little room to monitor for clients using incorrect/stale key_ids.  (A fairly standard 3-key rotation cycle means 3/4 of all expired key_id's would still appear valid to the issuer at any given time.)

**Comment by tfpauly** [comment]
Discussing leaving it at 8 bits to keep aligned with OHTTP and ECH, and adding more text about this area and the requirements for consistency checks.

**Comment by martinthomson** [comment]
I don't see alignment as a concern: the value is going to be conveyed in an 8 bit field, but you don't have to use all the bits.

Stronger emphasis on consistency is the direction I'd be looking for, definitely.

**Comment by chris-wood** [comment]
I think we ought to keep the consistency discussion primarily in the architecture document. Any objections to that, @martinthomson and @tfpauly?

**Comment by tfpauly** [comment]
There at least should be some strong pointers to that section in architecture, I think.
