### ISSUE TITLE
Redemption

### ISSUE THREAD

**Issue by martinthomson** [ietf-wg-privacypass/base-drafts#280]
The protocol descriptions in the protocol draft (Sections 5 and 6) don't include a heading for token redemption.  It looks like the finalization step is where some of that happens, but it seems fairly crucial for the draft to explain that clients to remove blinding and then construct a token that can be redeemed...*and then they send it to the origin*.

There is a similar problem in the architecture draft where the "redemption" protocol doesn't show the challenge-response flow, or even a spontaneous flow.  That is left for the section following, which covers issuance.

**Comment by chris-wood** [comment]
I think we can probably address this by including "end to end" examples in the architecture document. The auth-scheme and protocol documents try to focus on their respective protocols. That is, the auth scheme creates token challenges and then consumes tokens, whereas the issuance spec takes token challenges as input and produces tokens as output. @tfpauly, thoughts?
