### ISSUE TITLE
Bloated tables

### ISSUE THREAD

**Issue by martinthomson** [ietf-wg-privacypass/base-drafts#285]
The [table in Section 8.2](https://www.ietf.org/archive/id/draft-ietf-privacypass-protocol-07.html#table-4) of the issuance protocol draft is just too wide for this format.  Consider using a definition list instead, transposing the table, or finding a way to remove columns.

**Comment by chris-wood** [comment]
A list would be better, yeah. We discussed this briefly in #257.

**Comment by chris-wood** [comment]
Fixed in #290
