### ISSUE TITLE
Safe addition/removal of token_types by an issuer

### ISSUE THREAD

**Issue by plisiecki1** [ietf-wg-privacypass/base-drafts#287]
I believe there is a race condition if an issuer tries to add or remove `token_type`s in its directory.

When adding a token type, a client may see the a key for the new `token_type` in the directory and use it even though the origin may have a slightly stale directory.

When removing a token, a client may see still see the key for the old `token_type` in a slightly stale directory and use it even the the origin may already have refreshed its directory.

One potential way to address this would be to extend or replace key ordering with a designation of which key(s) are "active." The client would only pick "active" keys to make requests to an issuer, but origins would verify against all listed keys. A `token_type` could then be "rotated" in/out of use by having it appear for some time as inactive before activating it or removing it entirely.

**Comment by chris-wood** [comment]
Hmm, unless there's some sort of additional consistency mechanism in place, clients are not really expected to fetch or inspect the issuer's configuration. This is only useful information for the origin. This relates to how the information is cached, so I think we can address this and #289 at the same time.

**Comment by plisiecki1** [comment]
There is still some potential for skew even with cache-control. The update includes a new to refetch the config if there is evidence that it's stale, and that certainly could help in many cases.

Presumably an issuer must still support a key for some amount of time after removing it from the directory for at least the cache max-age. (Is that worth mentioning explicitly?)

A client that is using consistency may fail to validate a token key if it has a _fresher_ directory than the origin and the token_type has been removed. One option would be for consistency providers to keep old keys around for some time after they are removed from the directory. Another option would be for the client to try other token_types that were offered by the origin. Would it be helpful to mention somewhere (issuance protocol or maybe the http auth scheme?) that clients should try a different (supported) token_type if the first attempt fails?

**Comment by chris-wood** [comment]
There will always be potential for skew in a distributed system like this. We already note that the issuer can advertise multiple keys (sorted by order of preference) to address this particular problem:

> Issuers MAY advertise multiple token-keys for the same token-type to support key rotation. In this case, Issuers indicate preference for which token key to use based on the order of keys in the list, with preference given to keys earlier in the list.

I don't think we need to say anything more without just being confusing.
