### ISSUE TITLE
Issuer Request URI: URL? "text/plain"?

### ISSUE THREAD

**Issue by plisiecki1** [ietf-wg-privacypass/base-drafts#288]
> Issuer Request URI: A token request URL for generating access tokens.  For example, an Issuer URL might be https://issuer.example.net/example-token-request.  This parameter uses resource media type "text/plain".

Since this URI is intended to be used as a URL later in the protocol -- and the description in fact calls it a URL -- would it be cleaner to name the parameter "Issuer Request URL"/`issuer-request-url`?

What "thing" is actually `text/plain`? The directory itself is `application/json`, the resulting content is JSON (whose strings do not carry a notion of media types), and the token request/response using this URI use `application/private-token-request`/`application/private-token-response`.

**Comment by chris-wood** [comment]
I think just dropping the media type mention at all is probably best here. It's just a URL string, so let's just call it that. Does #296 work for you?

**Comment by plisiecki1** [comment]
That looks much better. Should the parameter also be `issuer-request-url`?
