### ISSUE TITLE
caching of issuer directories

### ISSUE THREAD

**Issue by plisiecki1** [ietf-wg-privacypass/base-drafts#289]
Most likely, clients and origins will be caching issuer directories.

Is it worth offering any guidance to client/origin implementations regarding caching? Is honoring cache-control response headers sufficient? And if so, should that be called out explicitly as a reminder to implementers (who might be building a custom cache or perhaps caching the parsed JSON content separately from an existing HTTP layer)?

Is it worth offering any guidance to issuers about how long they should assume directory changes will take to reach ~100% of clients and issuers? (My gut says no to this one -- but I am throwing it out in case others think it is worthwhile.)

**Comment by chris-wood** [comment]
Using cache control directives for this key material seems fine, provided it's done in accordance with your key rotation schedule.

**Comment by plisiecki1** [comment]
The proposed change addresses the primary concern of this issue.

> When use of an Issuer configuration results to token issuance failures

Typo? Should it be "results in"?

**Comment by chris-wood** [comment]
> Typo? Should it be "results in"?

Yep, fixed.
