### ISSUE TITLE
Issuer directories are underspecified

### ISSUE THREAD

**Issue by e271828-** [ietf-wg-privacypass/base-drafts#300]
There are several related issues in https://github.com/ietf-wg-privacypass/base-drafts/blob/main/draft-ietf-privacypass-protocol.md#configuration-setup:

1. Should the well-known location `/.well-known/token-issuer-directory` require mTLS? The two well-known public implementations previously highlighted by Apple disagree on this point.

Our opinion: mTLS should not be required for the token issuer directory.

2. `issuer-request-uri` is underspecified. Should this be an absolute URI, a relative URI, or allow either format?

Our opinion: We prefer relative URIs, and think either option should be supported. A relative URI is also used by at least one well-known public implementation.

**Comment by chris-wood** [comment]
> Should the well-known location /.well-known/token-issuer-directory require mTLS? The two well-known public implementations previously highlighted by Apple disagree on this point.

No. That's deployment specific decision.

> issuer-request-uri is underspecified. Should this be an absolute URI, a relative URI, or allow either format?

Either is fine, as evidenced by current implementations. We'll make this clear.
