### ISSUE TITLE
Stop leaning so hard on the authscheme draft

### ISSUE THREAD

**Issue by martinthomson** [ietf-wg-privacypass/base-drafts#304]
The architecture references \[AUTHSCHEME\] for key concepts far more than I expected.  For instance:

> As described in \[AUTHSCHEME\], there are a number of ways in which the token may vary, including:

Or:

> The Privacy Pass issuance protocol is a two-message protocol that takes as input a TokenChallenge from the redemption protocol ([AUTHSCHEME](https://ietf-wg-privacypass.github.io/base-drafts/draft-ietf-privacypass-architecture.html#AUTHSCHEME)], [Section 2.1](https://datatracker.ietf.org/doc/html/draft-ietf-privacypass-auth-scheme-07#section-2.1)) and produces a Token ([[AUTHSCHEME](https://ietf-wg-privacypass.github.io/base-drafts/draft-ietf-privacypass-architecture.html#AUTHSCHEME)], [Section 2.2](https://datatracker.ietf.org/doc/html/draft-ietf-privacypass-auth-scheme-07#section-2.2)),

Can the architecture define the messages in their own right, then point to \[AUTHSCHEME\] for example implementations?

**Comment by chris-wood** [comment]
Is the suggestion here to describe -- conceptually -- what Token and TokenChallenges are in the architecture document? If so, that seems quite reasonable.

**Comment by martinthomson** [comment]
Yeah.  An architecture is most useful if you don't have to dig into the details to understand it and those references are somewhat critical to comprehension.
