### ISSUE TITLE
Diagrams might be unclear

### ISSUE THREAD

**Issue by martinthomson** [ietf-wg-privacypass/base-drafts#305]
In this image:
![image](https://user-images.githubusercontent.com/67641/208595737-2b1f7670-5b27-4ff7-80e5-e36dc7b4f3df.png)

It isn't very clear where messages originate and who gets to see them.  In particular, it isn't clear where the TokenRequest originates (the Client) and whether the Attester gets to see it (¯\\(°\_o)/¯).

**Comment by tfpauly** [comment]
- Move diagram to section 3 (architecture). Also move much of the second intro paragraph down.
- Add more text about the actual steps to section 3, such as a numbered list

**Comment by tfpauly** [comment]
In here, introduce the basic privacy premise for how the redemption and issuance contexts are separated
