### ISSUE TITLE
What causes the client to perform attestation?

### ISSUE THREAD

**Issue by martinthomson** [ietf-wg-privacypass/base-drafts#322]
The issuance overview step 3 says that the Client and Attester interact to do whatever is necessary to convince the Attester to attest.  But there doesn't seem to be any pretext for this process to be initiated.  Step 4 says that the client requests issuance (via the Attester), which would provide the necessary cause to start the attesting process.  Should these steps be swapped?

**Comment by tfpauly** [comment]
Either the attester is an intermediary to the flow (which is what we're doing in practice), or it is a separate flow.

So the prerequisite is that the client knows it wants to request a token from an issuer, and then it does attestation.

**Comment by chris-wood** [comment]
Perhaps this could be made more clear if we say that the client, upon deciding it wants to invoke the issuance protocol, then begins the deployment-specific attestation process with its trusted attester? I can suggest some text for this.
