### ISSUE TITLE
Issuer-Client unlinkability mentions redemption contexts

### ISSUE THREAD

**Issue by martinthomson** [ietf-wg-privacypass/base-drafts#324]
I think that this definition is incorrect.  The latest sentence is from the definition of Origin-Client unlinkability:

> Issuer-Client unlinkability. This is similar to Origin-Client unlinkability in that a Client in an issuer context is indistinguishable from any other Client that might use the same issuer context. The set of Clients that share the same redemption context is referred to as a redemption anonymity set.

**Comment by chris-wood** [comment]
🤦 good catch. Copy-pasta error.
