### ISSUE TITLE
Contexts and unlinkability goals

### ISSUE THREAD

**Issue by martinthomson** [ietf-wg-privacypass/base-drafts#325]
The definition of the redemption/issuance/attestation contexts seem to exist primarily to support the different unlinkability goals in the document.  Let's take the redemption one, which is defined as:

> The interactions and set of information shared between the Client and Origin. This context includes all information associated with redemption, such as the timestamp of the event, Client visible information (including the IP address), and the Origin name.

<details>
<summary>A digression on perspective</summary>

Note that "Client visible" is probably ambiguous here; it could mean information about the client that is visible (though to whom?) or information that is visible to the client.

This suggests that your goal is establish a point of reference or perspective for these: in this case, the relevant perspective is that of an Origin.  But this was not my main point...
</details>

The corresponding unlinkability definition says:

> Origin-Client unlinkability. This means that given two redemption contexts, the Origin cannot determine if both redemption contexts correspond to the same Client or two different Clients. Informally, this means that a Client in a redemption context is indistinguishable from any other Client that might use the same redemption context. The set of Clients that share the same redemption context is referred to as a redemption anonymity set.

This is a little confusing, because you might conceive of the defines the context as enclosing a single interaction between the Client and Origin, but this implies that a context encompasses multiple interactions with either the same client or different clients (all of which are indistinguishable).  That makes the definition of the context seem like it lacks something.  Does this refer to the information that is provided within that context that might be used to identify a client, from the perspective of the server?

Finally, there is mention of an "an empty redemption context" in Section 3.1.  I had no idea how to interpret this claim.  Does empty refer to the set of clients? The set of interactions?  The information provided in that context?

**Comment by tfpauly** [comment]
The empty redemption context comment is talking about the `redemption_context` field of the challenge being empty / zero-length.

**Comment by chris-wood** [comment]
> Does this refer to the information that is provided within that context that might be used to identify a client, from the perspective of the server?

Basically, yeah, this is the idea. Perhaps framing it this way would be a more clear description. 

@tfpauly regarding "empty redemption context," maybe we just say "an empty token challenge redemption context," or something, to make it clear that this is referring to the challenge field described in Section 3.1?
