### ISSUE TITLE
Cardinality of different relationships

### ISSUE THREAD

**Issue by martinthomson** [ietf-wg-privacypass/base-drafts#326]
From a bullet point in Section 3.1:

> Each Issuer, in turn, determines which Attesters it is willing to accept in the issuance protocol. This means that if an Origin origin.example accepts tokens issued by Issuer issuer.example, and that Issuer in turn accepts different types of attestation from more than one trusted Attester, then a Client may use either of these trusted Attesters to issue and redeem tokens for origin.example. 

It seems like the challenge points to a single issuer and the issuer points to one or more attesters.  If this is the case, then it might be worth spending a paragraph or sentence on it rather than burying it in an example.  Also, at this stage, it is not clear why the Origin couldn't point to more than one Issuer, if it were willing to do so.  A forward reference to discussions about this limit here being necessary to prevent widening the cross-contextual flow of information; though I believe that if the client were to be consistent in its choice, there is no additional information leak (other than perhaps something inherent to the client's choice).

**Comment by chris-wood** [comment]
Agreed. As part of #333, I think we can address this with a section on trust relationships and their cardinality.
