### ISSUE TITLE
Diagrams

### ISSUE THREAD

**Issue by martinthomson** [ietf-wg-privacypass/base-drafts#330]
This is a little hard to process...  An inbound PR I have proposes a change to the first diagram that might help here.  A little work on this is probably necessary.

![image](https://user-images.githubusercontent.com/67641/218657903-b8cbbd9e-04e7-48c9-9b1e-0431c6fe6843.png)

**Comment by martinthomson** [comment]
A few things:

When drawing arrows on lines, the line will connect with the line neatly if there is a connector or if there is an arrow adjacent to the line:

```aasvg
|    |
+--->|
|    |
```

This puts the arrow on the line, which renders a gap in the line.  Avoid this:

```aasvg
|
<----
|
```

The bottom-left corner here is not curved, because the detection of corners needs three characters: the corner and a line either side of that, so...

```aasvg
|
 `--
```

Not:


```aasvg
----->
 `--
```

**Comment by chris-wood** [comment]
@martinthomson can you say more about how it's hard to process? As we recently discussed, we're burdened by being too close to this work, so it's hard for me to see a substantial difference between the diagram in this issue and that which you proposed in the recently merged PR. 

Is it not clear who touches or sees each message? Part of the challenge in this particular diagram -- and any in which the attester is party to the protocol -- is that the attester may be inline or may not be! The architecture does not _require_ the attester to be inline, it really only requires that the token request from a client be somehow blessed by the attester. I'll think about ways to better visualize this, but clarification about the source of confusion would be super helpful.

**Comment by martinthomson** [comment]
For me, the hardest part of these diagrams is that the start and end of the end of the arrows aren't really attached to anything in particular.  You rely on horizontal alignment a fair bit (the arrow starts approximately under the label "Issuer", so it's probably a message from the issuer).  In comparison, the diagram I provided had lines and boxes connecting them.

This is probably a more illustrative example:
![image](https://user-images.githubusercontent.com/67641/220018066-b0a67c21-02c1-4eb5-88aa-0ecde3bea074.png)
Are the TokenRequest and TokenResponse labels *on* the lines?  Where do these arrows start?

Then there are the formatting issues, some of which I will concede are specific to aasvg, see the above comment.

**Comment by chris-wood** [comment]
Thanks -- that's helpful. I think #344 should resolve the confusion.
