### ISSUE TITLE
Can the Origin distinguish per- and cross-origin tokens?

### ISSUE THREAD

**Issue by martinthomson** [ietf-wg-privacypass/base-drafts#332]
It seems like this is not the case (from Section 4.3):

> If there is only a single Origin, then per-Origin tokens are not appropriate in this model, since the Attester can learn the redemption context. However, the Attester does not learn whether a token is per-Origin or cross-Origin.

This implies something about the way in which per-origin tokens are attested that does not follow from any of the previous text.  But I don't know what.  Is it the case that the client needs to communicate the origin that a per-origin token needs to be bound to?  Does this assume that the issuer in this deployment configuration is receiving this information via the attester?  Why is it that the client can't use a proxy (or OHTTP) to request a token from the issuer?

**Comment by martinthomson** [comment]
None of this is really clear from the description in the architecture.

**Comment by chris-wood** [comment]
@martinthomson does the text in [Section 3.1](https://ietf-wg-privacypass.github.io/base-drafts/draft-ietf-privacypass-architecture.html#name-redemption-protocol), which describes the ways in which token challenges can vary, not suffice? If not, can you help us understand what's missing?

**Comment by martinthomson** [comment]
What is missing is a description of the *sort* of information that is exchanged between different roles in these cases.  That might be aided by including a reference to specific fields (like `origin_info`) or by talking about the requirements more generally.

The problem with the text in Section 3.1 is that it says the token is bound to an origin or not, but it doesn't really give enough context to understand how this might happen.  Tommy's explanation about origin is correct and obvious, but not particularly satisfying as an answer, because it's nearly a truism (obviously you need an origin for something to be origin-bound).

I didn't realize this until I'd spent some time thinking about this, but when the origin needs tokens to be bound in some way to information **from the origin**[^1], that information needs to make it to the issuer.  That the issuer needs to *see* that information seems to be the primary motivation for the attester/issuer split.  

[^1]: The identity of the origin is the obvious thing the origin might need to provide.  It's the only thing you talk about in the document, but there is a more general statement to be made: it might be necessary to bind to arbitrary information that the origin supplies, which the issuer also needs to see in order to construct a token.

For instance, with a blind signature, the client could use the issuer as a signing oracle and include the origin in the data that is signed, but that might make token forgery for arbitrary origins trivial without a ZKP to accompany the signing request.  The bit that makes this hard to grok is that the ZKP design is entirely valid here, so why do you need the attester/issuer split?  

My best answer is that you don't, except when it is easier to build a system that doesn't rely on cryptography that is generally pretty unpleasant to work with.

The split, avoids a situation where one entity simultaneously sees client identity or client-specific information (which is sometimes necessary for the attester) and information about the usage context (again, sometimes necessary for the issuer).  If it weren't for that, the issuer and attester could be the same entity.   This is an important piece of the architecture, but the document never really *says* that.  The information about per-origin tokens just isn't connected to the description of the different roles.

**Comment by chris-wood** [comment]
In thinking about this issue some more, I think we can probably resolve this comment by building on the trust relationships and cardinality discussion that's in a separate PR. The text in the original comment refers to the fact that, in deployments where an there is an attester that uses an issuer that is configured for only one origin, say, A.com, then any token request for a _specific_ origin must necessarily be for A.com. 

I think the primary problem here is that text is a bit confusing in that, well, if there's an issuer that only supports one origin, then how can it work for cross-origin tokens? I will try to simplify.

**Comment by chris-wood** [comment]
As I started to dig into that clarification, Martin's original idea to start talking about things in terms of information flow really seemed like the natural conclusion, so that's what #346 tries to do. Please review!
