### ISSUE TITLE
Bearer tokens

### ISSUE THREAD

**Issue by martinthomson** [ietf-wg-privacypass/base-drafts#334]
This system extensively uses tokens that are only loosely bound to usage contexts.  Possession of a token is pretty much all that is necessary. That means that tokens might be stolen or hoarded and then replayed.  The architecture draft says nothing about this as a risk, but it probably should.

**Comment by chris-wood** [comment]
Agree, especially for for cached tokens. I thought we had mentioned this somewhere, but if not, let's make sure it's included.
