### ISSUE TITLE
Add base64 examples to test vectors

### ISSUE THREAD

**Issue by colinbendell** [ietf-wg-privacypass/base-drafts#352]
A common bug I have seen with engineering teams implementing PAT is that they don't pad base64url encoded challenges. This is compounded by the lack of feedback from the UA. However, in this case, the padding is not needed for successful base64 decode because the lengths are known. Additionally, introducing `=` padding requires additional quoting of the fields which adds both visual and non-value noise to the exchange. 

`WWW-Authenticate: PrivateToken challenge="abc123==", token-key="def456=="`
vs
`WWW-Authenticate: PrivateToken challenge=abc123, token-key=def456`

I can appreciate the desire to make the spec less ambiguous to reduce the burden on the UA. However, given that there are a limited number of UAs but millions of origins, there is a greater chance that origins will be unknowingly misconfigured. Therefore it would improve developer ergonomics for origins if the UA was expected to be more flexible in the decode.

**Comment by tfpauly** [comment]
The padding requirements date back to https://github.com/tfpauly/privacy-proxy/pull/165

This was chosen to be strict about formatting, and minimize long-term interop issues by allowing a single approach. I doubt we'd want to change that.

See the discussion in this document about flexibility: https://www.ietf.org/archive/id/draft-iab-protocol-maintenance-12.html#name-flexible-protocols

**Comment by tfpauly** [comment]
Discussed with authors — proposing to resolve this by adding the HTTP auth headers to the test vector section to make it very clear how to parse the base64, etc.
