### ISSUE TITLE
Address Developer Ergonomics by providing UA feedback for malformed challenges

### ISSUE THREAD

**Issue by colinbendell** [ietf-wg-privacypass/base-drafts#353]
A common bug I have seen with engineering teams implementing PAT is that they don't pad base64url encoded challenges (see https://github.com/ietf-wg-privacypass/base-drafts/issues/352). This easily goes un-noticed and impacts adoptions. The root challenge is that automated integration tests with PAT aren't possible compounded by the lack of feedback interfaces from the UA to report of a malformed challenges. 

I created a [few tools](https://private-access-token.colinbendell.dev/) to [help test](https://private-access-token.colinbendell.dev/debug.html) for some of the common errors. However, malformed rejection from the UA is still challenging. 

For example, the current version of the spec requires base64url with padding, and with padding the fields should be quoted. A developer following this spec would run into errors today because the current implementation in iOS and macOS reject quoted fields. This causes many hours of developer time trying to triage and investigate these kinds of errors. 

It would help if there was a standard mechanism for a UA to clearly report if a challenge is being rejected because it was malformed. A few possible suggestions:
1. send an http header, or a variant of the Authorization header signalling this malformed challenge on the next request. For example `Authorization: PrivateToken error="Malformed challenge"`
2. integrate the spec with the [ReportingAPI](https://w3c.github.io/reporting/) allowing for out of band, and privacy preserving feedback to the origin.

Having such a feedback mechanism will also allow for easier UA adoption by enabling WPT tests.

**Comment by tfpauly** [comment]
While I understand that there are cases where this can be useful for debugging implementations, I don't think this belongs in the core spec — it seems more appropriate for an extension.

- Having `Authorization` header on a subsequent request provide information about a previous challenge seems to be a new mechanism entirely, and we'd need to do more evaluation of the properties of that for privacy and likability.
- Generally, we don't want to tell origins why tokens failed, as a privacy mechanism.
- This case of malformed challenges seems to be mainly a case for development debugging, not something expected in production.
