### ISSUE TITLE
idnits in auth-scheme

### ISSUE THREAD

**Issue by bemasc** [ietf-wg-privacypass/base-drafts#358]
From [the idnits tool](https://author-tools.ietf.org/api/idnits?url=https://www.ietf.org/archive/id/draft-ietf-privacypass-auth-scheme-09.txt&submissioncheck=True):

~~~~
  == Outdated reference: A later version (-11) exists of
     draft-ietf-privacypass-architecture-10

  == Outdated reference: A later version (-10) exists of
     draft-ietf-privacypass-protocol-08

  -- Duplicate reference: RFC8446, mentioned in 'RFC8446', was also mentioned
     in 'TLS13'.
~~~~

**Comment by tfpauly** [comment]
The first two will get automatically handled when we update. The third is a simple fix.
