### ISSUE TITLE
Should token-issuer-directory be private-token-issuer-directory?

### ISSUE THREAD

**Issue by dvorak42** [ietf-wg-privacypass/base-drafts#373]
It seems a little odd that two out of three of the IANA registrations are for "private-token-FOO" while the directory is just "token-FOO".

Is there a reason for the discrepancy? Might be worth aligning those together?

**Comment by chris-wood** [comment]
Good point! I'd be fine with renaming this such that they are all aligned with 'private-token' prefixes. This only affects clients that consume the directory, which should be fairly easy to do right now. @tfpauly, any issues on your end?

**Comment by chris-wood** [comment]
I was thinking about the attester, which might be fetching it and enforcing a particular content type.

**Comment by tfpauly** [comment]
Yes, but I think we could do a transition if needed.
