### ISSUE TITLE
token_type scope clarification

### ISSUE THREAD

**Issue by chris-wood** [ietf-wg-privacypass/base-drafts#382]
From @paulwouters

        "token_type" is a 2-octet integer, in network byte order. This
        type indicates the issuance protocol used to generate the
        token. Values are registered in an IANA registry, Section
        5.2. Challenges with unsupported token_type values MUST be
        ignored. This value determines the structure and semantics of
        the rest of the structure.
        [ more fields of the structure ]

If now describing more structures, those can only be valid for a specific
value of token_type. This should then be mentioned here. (same issue in
"Token Redemption" section). Also, I don't see any non-grease value added
to the IANA registry. I assume 0x0002 will be added for [ISSUANCE] and
that the structures here are for that use case? If so, that deserves
clarification. If not, I think this also might need some rephrasing?

**Comment by paulwouters** [comment]
I dont think this addressed my point.

The TokenChallenge message has the following structure:

struct {
    uint16_t token_type;
    opaque issuer_name<1..2^16-1>;
    opaque redemption_context<0..32>;
    opaque origin_info<0..2^16-1>;
} TokenChallenge;

The structure fields are defined as follows:
"token_type" is a 2-octet integer, in network byte order. This type indicates the issuance protocol used to generate the token. Values are registered in an IANA registry, [Section 5.2](https://datatracker.ietf.org/doc/html/draft-ietf-privacypass-auth-scheme-10#token-types). Challenges with unsupported token_type values MUST be ignored. This value determines the structure and semantics of the rest of the structure.

To me, what you are describing is:

```
struct {
    uint16_t token_type;
    opaque blob<0..2^16-1>;                        (or 2^32 I guess)
} TokenChallenge;

```
Where for token_type is 2, you have the opaque blob be:

```
    opaque issuer_name<1..2^16-1>;
    opaque redemption_context<0..32>;
    opaque origin_info<0..2^16-1>;

```

for token_type = 3, there might not be an issuer_name, etc.

**Comment by paulwouters** [comment]
either that, or perhaps you mean:
```

struct {
uint16_t token_type;
opaque issuer_name<1..2^16-1>;
opaque redemption_context<0..32>;
opaque origin_info<0..2^16-1>;
opaque other_stuff<0..2^16-1>;                         0 for token_type=2
} TokenChallenge;
```

**Comment by chris-wood** [comment]
What this PR says is everything after `token_type` is determined by `token_type`. I'm not seeing how that's not clear, so maybe you could suggest some specific changes to clarify?

**Comment by paulwouters** [comment]
You define a struct but that struct is not generic, even though you pretend it is. I don't understand how to make it more clear than the comments I already left above your comment?

**Comment by chris-wood** [comment]
@paulwouters given that this has been through WGLC without such confusion, I think you will need to suggest concrete changes to clarify what you have in mind.

**Comment by paulwouters** [comment]
That is better. But I'm still confused about including multiple optional fields and how you know which of potential multiple optional fields is present.  While most of that problem is not other documents problem, there are multiple optional fields right here in this generic advise that I dont think a parser can determine (unless optional has a meaning of "add a 0byte for zero length of this field (in which case I would not call it optional)

**Comment by tfpauly** [comment]
@paulwouters the optional fields are length-prefixed, so they have lengths of 0 when empty. So they're "optionally non-empty".

**Comment by paulwouters** [comment]
I think better terminology than "optional" should be used if they will always put in a length field. It seems the field is not optional at all but may be zero length

**Comment by tfpauly** [comment]
@paulwouters updated to this:

> - "redemption_context" is a field that is either 0 or 32 bytes, prefixed with a single
>  octet indicating the length (either 0 or 32). If value is non-empty, it is a 32-byte value
>  generated by the origin that allows the origin to require that clients fetch tokens
>  bound to a specific context, as opposed to reusing tokens that were fetched for other
>  contexts. See {{context-construction}} for example contexts that might be useful in
>  practice. Challenges with redemption_context values of invalid lengths MUST be ignored.
> 
>  - "origin_info" is a string that is either empty, or contains one or more origin
>  names that allow a token to be scoped to a specific set of origins. The string
>  is prefixed with a 2-octet integer indicating the length, in network byte
>  order. If empty, any non-origin-specific token can be redeemed. If the string
>  contains multiple origin names, they are delimited with commas "," without any
> whitespace. If this field is not empty, the Origin MUST include its own name
> as one of the names in the list.
