### ISSUE TITLE
issuer_name clarification

### ISSUE THREAD

**Issue by chris-wood** [ietf-wg-privacypass/base-drafts#383]
From @paulwouters

>  opaque issuer_name<1..2^16-1>

with:

> The string is prefixed with a 2-octet integer indicating the length

these two don't go well together. If the value itself isn't length-describing,
like ASN.1 things, then the field should be shown as a separate field in the
struct? Especially since issuer_name claims its minimum length is 1 and so it
cannot contain the 2 octet length field. If the 2^16-1 implies the two octet
length, then perhaps a note is useful to state if this field is omitted, two
zero bytes are present? That is also the only way one could distinguish the
two optional fields redemption_context and origin_info if only one was included?
(this might be obvious to TLS13 readers and its syntax, but as specified, I
don't find it very clear, and I suspect non-TLS implementers might not either)

**Comment by paulwouters** [comment]
I'm still unclear on some parts.

based on:

struct {
    uint16_t token_type;
    opaque issuer_name<1..2^16-1>;
    opaque redemption_context<0..32>;
    opaque origin_info<0..2^16-1>;
} TokenChallenge;

Can you show me the bytes for:

1) token_type = 2, issuer_name "nohats.ca",  redemption_context="example.com", no origin_info

and

2) token_type = 2, issuer_name "nohats.ca",  no redemption_context and origin_info="example.com"

**Comment by chris-wood** [comment]
The redemption context is _not_ an origin name. As described in the spec, it's either a 0 or 32 byte value. Anyway, here are the bytes, generated from actual code.

1. token_type = 0x0002, redemption_context = `5218ea3062d78299246161ca4cd6a0d22ad688a443b5b7fe60941e659b554e39`, issuer_name = "nohats.cs", origin_info = nil, challenge = `000200096e6f686174732e6361205218ea3062d78299246161ca4cd6a0d22ad688a443b5b7fe60941e659b554e390000`.
2. token_type = 0x0002, redemption_context = nil, issuer_name = "nohats.cs", origin_info = "example.com", challenge = `000200096e6f686174732e636100000b6578616d706c652e636f6d`.

3. token_type = 0x0002, redemption_context = nil, issuer_name = "nohats.cs", origin_info = "foo.example,bar.example", challenge = `000200096e6f686174732e6361000017666f6f2e6578616d706c652c6261722e6578616d706c65`
