### ISSUE TITLE
Define extension for public verifiability

### ISSUE THREAD

**Issue by chris-wood** [ietf-wg-privacypass/base-drafts#40]
Per the charter.

**Comment by alxdavids** [comment]
Potential instantiation highlighted by @wbl on the mailing list: https://mailarchive.ietf.org/arch/msg/privacy-pass/BDOOhSLwB3uUJcfBiss6nUF5sUA/. Do we want to consider any other schemes?

**Comment by chris-wood** [comment]
Resolved in #87.
