### ISSUE TITLE
Auth scheme: update rationale for base64 padding guidance

### ISSUE THREAD

**Issue by DavidSchinazi** [ietf-wg-privacypass/base-drafts#412]
In the [current auth scheme draft](https://www.ietf.org/archive/id/draft-ietf-privacypass-auth-scheme-11.html#section-2.1), `challenge` and `token-key` are currently defined as base64url-encoded values. The draft also states:
> Since the length of the challenge is not fixed, the base64url value MUST include padding.

This sounds like a misunderstanding of how base64 padding works. Padding is only required when concatenating two base64 messages. Here's an example:

* `hello` ASCII encodes as base64 `aGVsbG8=`
* `base` ASCII encodes as base64 `YmFzZQ==`

On the decoding side, `aGVsbG8` is non-ambiguous: it decodes just as well as `aGVsbG8=`. Similarly, if you see `YmFzZQ` you know how many bytes there are and it decodes fine. The problem arises if you concatenate: `aGVsbG8=YmFzZQ==` decodes to `hellobase` (assuming your decoder supports this which many don't), but `aGVsbG8YmFzZQ` decodes to `hello\`.

In the context of this draft, the message is strongly delimited (ends with the end of the header, or with a whitespace or a comma etc.) so there is no opportunity for concatenation.

This document shouldn't be requiring padding.

**Comment by tfpauly** [comment]
I am happy to change the explanation for why the padding is present, but I would prefer to not change the padding at this point to have a breaking change, that doesn't add any significant value. I prefer to have a spec with a consistent approach (one or the other), and the spec for base64 does by default require padding. Of course, we could choose to override that here (as RFC4648 allows) but I don't see a strong reason to do so.

https://www.rfc-editor.org/rfc/rfc4648#section-3.2

>    In some circumstances, the use of padding ("=") in base-encoded data
>    is not required or used.  In the general case, when assumptions about
>    the size of transported data cannot be made, padding is required to
>    yield correct decoded data.
> 
>    Implementations MUST include appropriate pad characters at the end of
>    encoded data unless the specification referring to this document
>    explicitly states otherwise.

This also allows the base64 string for the keys to be safely copied into other contexts where it might get concatenated, without risk of losing the length. If we change the advice, we would need to add security warnings about using these strings in other contexts.

**Comment by DavidSchinazi** [comment]
RFC 4648 recommends including padding because it assumes that concatenation can take place, which really isn't the case here. Copying these strings into other contexts and concatenating them doesn't make any sense to me in this case. What does concatenating challenges mean? Or concatenating public keys? And even if that did make sense, why would you concatenate base64 instead of concatenating the decoded binary?

Preferring to avoid wire format changes at this point in the timeline is totally reasonable though. If this is too much of a deployment problem, then keeping the wire format as-is but removing the rationale is a viable option.

**Comment by tfpauly** [comment]
Happy to make a PR to remove that rationale.

**Comment by tfpauly** [comment]
@DavidSchinazi please check #413
