### ISSUE TITLE
Define extension for private metadata bit variant

### ISSUE THREAD

**Issue by chris-wood** [ietf-wg-privacypass/base-drafts#42]
We say it's possible, but let's be a bit more concrete.

**Comment by alxdavids** [comment]
I think this will depend on having a draft specification of the underlying cryptographic functionality.

**Comment by martinthomson** [comment]
Just so this is on the record somewhere: https://eprint.iacr.org/2020/072  (which is one possible version of the crypto for this).

**Comment by chris-wood** [comment]
Now that the protocol and architecture are configured to allow extensibility by new token types, I'm going to close this issue for now. When the time comes that we feel we want to introduce an issuance protocol with private metadata, one can cut an individual draft that defines it without any changes to the architecture, protocol, or auth-scheme docs.
