### ISSUE TITLE
Specify redemption mode in public config

### ISSUE THREAD

**Issue by alxdavids** [ietf-wg-privacypass/base-drafts#44]
Servers should specify accepted redemption modes that they allow as a list associated with their public configuration. This would be a subset of the list `["single", "proxy", "async", "public"]` corresponding to the redemptions modes in https://tools.ietf.org/html/draft-davidson-pp-architecture-01#section-5.

In all modes except "single" we should also allow optional specification of _allowed_ verifiers that can ask for tokens on the server's behalf. If one of these verifiers asks for a client token associated with the server, then the client will first check this list to ensure that the verifier exists before sending the token. This ensures that clients don't reveal which tokens they hold to untrusted verifiers.

cc @chris-wood @dvorak42

**Comment by chris-wood** [comment]
Interesting. To what extent are these modes determined by the underlying cryptographic protocol? (The public redemption mode, for example, is certainly dependent on the underlying protocol.)

**Comment by alxdavids** [comment]
So the first 3 modes are essentially all symmetric running modes, but they should be agnostic to the specific choice of protocol. In deed `public` requires public-key analogues of Privacy Pass, but it shouldn't depend on the actual instantiation (in terms of cryptographic ciphersuite). Does this answer your question?

**Comment by alxdavids** [comment]
Requires moe discussion around what information is allowed in the config. This change would imply allowing identifiers for verifiers in the config, which could be URLs etc, but this may narrow use-cases. We should think about this more.

**Comment by chris-wood** [comment]
It *seems* like a configuration should contain the minimal cryptographic information necessary to run the protocol securely. But this is indeed quite interesting because *who* clients run the protocol with may impact security. We could maybe allow for (sequences of) opaque identifiers to be provided in the config? Not sure.

**Comment by chris-wood** [comment]
Overcome by events. Closing.
