### ISSUE TITLE
Issuer identification using an "authority"

### ISSUE THREAD

**Issue by martinthomson** [ietf-wg-privacypass/base-drafts#440]
> "issuer_name" is an ASCII string that identifies the issuer using the format of the authority portion of a URI as defined in Section 3.2 of [URI].

This is a little surprising to me, which suggests that it might need an explanation.

I might even suggest that this is dangerous, in that it can include `userinfo`, which seems like it might be harmful in this context (though I can't exactly see why).

Would a web origin [RFC6454] be a better choice?

**Comment by tfpauly** [comment]
The origin definition in RFC6454 seems like it would include the scheme as well, which is not quite what we want here. The goal is to have it be the hostname+(optional port). Agreed that we don't want a `userinfo`, although maybe we can just spell that out.

**Comment by martinthomson** [comment]
I know that origin is a change, but host+port isn't really meaningful without some sort of framework under which it operates.  I think that you are OK with limiting this to HTTPS, so the scheme is probably redundant.  That leaves one question: does a bare host mean any HTTPS endpoint on any port on that host, or is it the service on port 443?

**Comment by tfpauly** [comment]
Indeed, the scheme for HTTPS is implied/redundant here. And yes, the bare host means port 443. Good stuff to clarify.

**Comment by tfpauly** [comment]
Proposal is to explain more clearly these bounds (no user info, implied 443 if no port) and define after the list of issuer_name and origin_info parameters, that both refer to.
