### ISSUE TITLE
Explain the functioning of origins in the challenge

### ISSUE THREAD

**Issue by martinthomson** [ietf-wg-privacypass/base-drafts#441]
There is an optional list of origins in the challenge, but the purpose of the field is not explained.

If I were to guess, the requirement to include the current server in the list means that clients are expected to retrieve tokens for that set of origins and -- if they receive extra -- use those tokens if challenged by any of the listed origins (provided that the other parameters match).

Section 2.1.2 almost says this, but there seems to be a missing link somewhere.

**Comment by tfpauly** [comment]
Section 1 does describe this:
```
In addition to working with different token issuance protocols, this scheme optionally supports use of tokens that are associated with origin-chosen contexts and specific origin names.
```

The reason is to let you have a particular token work across origins, or be specific to origins (when you've prefetched a bunch).

**Comment by martinthomson** [comment]
That really doesn't say what the semantics are.  That is, the expectation is that the same challenge will be issued by all of the listed origins AND that the client can use a token retrieved for any of those challenges to answer any other challenge, without adhering to its normal rules about restricting information to a single origin.

Note that the use of the word "origin" is hugely confusing in this context, so you will need to be more careful than I am being.
