### ISSUE TITLE
Binding requests to connections

### ISSUE THREAD

**Issue by martinthomson** [ietf-wg-privacypass/base-drafts#446]
> For example, double spend state for unique, per-request redemption contexts only needs to exist within the scope of the request connection or session. 

This is probably not a good idea.  Clients will expect to be able to make a new request over a new connection and will probably not request fresh issuance if a request with a token fails.

(Also, "request connection" is not a concept in HTTP.)

**Comment by chris-wood** [comment]
Is this comment trying to say that it's OK to replay a token over the same connection? If so, I would agree with that, since linkability already exists at the connection layer.
