### ISSUE TITLE
WWW-Authenticate is not a request-response protocol

### ISSUE THREAD

**Issue by martinthomson** [ietf-wg-privacypass/base-drafts#449]
There are a few instances where this assumes that clients will automate their response to receiving a challenge.  That's not really how HTTP authentication works.

**Comment by tfpauly** [comment]
@martinthomson can you clarify which instances you're referring to? While it's true that it's not a request-response protocol, it's also not a case where we need user interaction in order to re-issue a request, so it is some cases "automated".

**Comment by tfpauly** [comment]
Improved some of this in #477. Instead of talking about response, this now talks about:

> Upon receipt of a challenge, a client validates the TokenChallenge structure
>  before taking any action, such as fetching a new token or redeeming a token
>  in a new request.

Can add some more
