### ISSUE TITLE
Greasing

### ISSUE THREAD

**Issue by martinthomson** [ietf-wg-privacypass/base-drafts#450]
> To mitigate the risk of deployments becoming dependent on tokens, clients and origins SHOULD grease their behavior unless explicitly configured not to. In particular, clients SHOULD ignore token challenges with some non-zero probability. From the origin's perspective, ignoring a token challenge is indistinguishable from the issuance protocol failing for arbitrary reasons (excluding what can be inferred from latency between the client and origin interaction). Likewise, origins SHOULD randomly choose to not challenge clients for tokens with some non-zero probability. Moreover, origins SHOULD include random token types, from the Reserved list of "greased" types (defined in Section 5.2), with some non-zero probability.

I have no idea how to implement greasing here.  Ignoring a challenge is easy, but you can't just ignore the fact that your request failed with a 401 status code.

**Comment by tfpauly** [comment]
I'm not sure what the confusion here is. The greasing cases we list are:
- Client chooses to not authenticate with a token
- Origin chooses to not send a token challenge
- Origin chooses to send greased token type challenges

Can you be more specific about what change you'd like to see?

**Comment by martinthomson** [comment]
Choosing not to do something is not greasing, it's doing nothing.  Greasing using bogus token types is greasing, but that is not what this seems to be aiming at.

(FWIW, This is one of your examples of where the text vaguely treats a challenge as a request and the subsequent request as a response to that.)

**Comment by tfpauly** [comment]
This is where we need better terminology for behavioral variation. We can change that line to say "add random variance to their behavior" instead of grease.

**Comment by martinthomson** [comment]
That wasn't my point.  My point was that a client has a goal in mind.  Refusing to supply a token sounds fine in isolation. However, if the result is that they get a 4xx rather than a 2xx, they will go and get the token.  Because the 2xx is what they want, not some abstract concept like greasing.

**Comment by chris-wood** [comment]
Perhaps the issue is that we call "doing nothing" and "sending random values" greasing, when what @martinthomson seems to be suggesting is that the latter is the only thing that's actually greasing (according to the ill-defined meaning we have)? I don't think we need to be strict about the meaning of grease.

**Comment by tfpauly** [comment]
I was suggesting calling it varying behavior, but Martin is pointing out that a client may not want to behave differently for a 4xx and just not authenticate.

In practice, for captcha-interaction cases, I think it actually is totally fine to then ignore these — in these cases, a client may not always be able to present a token anyway, so it has to be able to handle not having a token. Certainly other deployment use cases may be different.

**Comment by chris-wood** [comment]
So, "origins SHOULD include random token types" is definitely grease, per the usual definition. The other stuff can be called "varying behavior" or whatever, I don't feel strongly. Clients that choose to just not authenticate given a 4xx and challenge are still adhering to the text, so I don't get the problem here.
