### ISSUE TITLE
Consider not including a private use range

### ISSUE THREAD

**Issue by martinthomson** [ietf-wg-privacypass/base-drafts#451]
RFC 6648 carries a useful lesson about how private use can leak into wider deployment.  That suggests that people looking to use stuff for private reasons can just pick a random codepoint to use.  There is still a risk of collision if it escapes into the wild, but that is more likely the case if they are forced to draw from a smaller "private use" range.

**Comment by chris-wood** [comment]
I also do not care about this bike shed. @smhendrickson would you be OK choosing a random codepoint?

**Comment by smhendrickson** [comment]
That works for me. I'll send a PR for auth scheme to remove this, and update the [extensions draft](https://chris-wood.github.io/draft-wood-privacypass-auth-scheme-extensions/draft-wood-privacypass-auth-scheme-extensions.html#section-5-5) to match.
