### ISSUE TITLE
Replay attacks via 0-RTT

### ISSUE THREAD

**Issue by martinthomson** [ietf-wg-privacypass/base-drafts#454]
There is no inherent problem with a replay of a token.  A problem only exists if replay occurs and the request that it authorizes has some sort of unwanted side effect.  That's not a problem with this document, so I'm not sure that you need to cite that document.

**Comment by chris-wood** [comment]
This seems like it would be resolved by an extension to #461. In particular, text that suggests replaying in an otherwise linkable context (like the same connection) is fine.

**Comment by tfpauly** [comment]
Yes, I agree we can have a simple change here, but let's do a new PR for that since it requires touching different parts of the doc too.
