### ISSUE TITLE
Flush on network change

### ISSUE THREAD

**Issue by martinthomson** [ietf-wg-privacypass/base-drafts#456]
> As discussed in Section 2.1, clients SHOULD discard any context-bound tokens upon flushing cookies or **changing networks**, to prevent an origin using the redemption context state as a cookie to recognize clients.

(Emphasis mine) I missed this first time around, but the requirement to drop state when changing networks is not necessary in many cases.  The reason to drop state is if you believe that the tokens would allow you to be recognized in a way that is unwelcome.

Most browser clients will retain site-specific state when they move, so this requirement would be pointless.

**Comment by tfpauly** [comment]
If the client does not retain site-specific state, and the context can be related to the client IP, etc, then it should flush the state. We can clarify that this is only useful when other state isn't being shared.

**Comment by martinthomson** [comment]
The server is the one that cares about the binding to IP in that case.  The client doesn't really know or care.  Maybe it will try to access the resource with a token that won't be accepted, which is fine because the server can just ask for another token.

**Comment by tfpauly** [comment]
If the redemption context was specific to a particular client IP, or client subnet, etc, the server could try to trial-verify tokens with a different client IP or subnet than the one the client is using to see if the token was generated using a challenge from a previous context on a particular IP — essentially, it lets a server guess if the client had a previous context, and verify it using the token.
