### ISSUE TITLE
Timing correlation is worse than this makes out

### ISSUE THREAD

**Issue by martinthomson** [ietf-wg-privacypass/base-drafts#458]
The following conditions, if all met, produces pretty poor privacy properties:

* A client that automatically executes issuance in response to receiving a 401 with a TokenChallenge.
* An attester that is exposed to identifying information about the client.
* An attester or joint attester/issuer that is willing to collude with the origin.

In cases where the origin, attester, and issuer are the same entity, this is particularly bad.

It seems like the only defense is to inject [delays](https://github.com/ietf-wg-privacypass/base-drafts/issues/457).  These have to be added both before and after requesting issuance.  For that to work, it is necessary to understand the rate at which that attester is being used so that the anonymity set size can be tuned.

There's a version of this where the attester is trusted not to collude with origins.  With a distinct issuer, the attester might shield the issuer from any identifying information.  If there is a joint attester/issuer, then having that entity be more trusted and distinct from the origin also works.  Either model -- the former of which being what Apple uses -- can address this concern.

(Also, this text should point to Section 6.3 of the architecture, not the whole doc.)

**Comment by tfpauly** [comment]
I largely think this should be addressed by improving the architecture references, since it's a property of the architecture more than a specific way to instantiate challenge/redemption. But we can emphasize this more.

**Comment by chris-wood** [comment]
I don't see anything we can meaningfully do here beyond citing the architecture document. Yes, timing attacks will exist and they will never really go away. This is not unique to Privacy Pass. I think we have to accept that the low latency or on-demand nature of the protocol will mean they exist. That seems like something we could further clarify in the architecture document, and then as Tommy suggests just lean more heavily on that from the auth-scheme document.
