### ISSUE TITLE
Describe privacy implications of underlying transport protocol(s)

### ISSUE THREAD

**Issue by chris-wood** [ietf-wg-privacypass/base-drafts#48]
Token issuance and redemption flows from the same IP address, for example, would be linkable, but this isn't a break in the privacy pass protocol. We should discuss these orthogonal privacy considerations.

**Comment by chris-wood** [comment]
I think this is already addressed [in the draft](https://github.com/ietf-wg-privacypass/base-drafts/blob/master/draft-ietf-privacypass-architecture.md#client-identifying-information-client-ip). @alxdavids, if you agree, can we close this?

**Comment by alxdavids** [comment]
Yep, good point, closing.
