### ISSUE TITLE
Token expiration

### ISSUE THREAD

**Issue by chris-wood** [ietf-wg-privacypass/base-drafts#49]
There's currently no text around token expiration. Minimally, we could say that tokens expire when issuer (and verifier) keys rotate. Do we also want to bake in mechanisms for expiration to be cryptographically bound to issued tokens? For example, one might imagine using PMB-like constructions to encode an expiration "epoch" into the metadata bits. The single metadata bit variant would allow two epochs that way. 

@dvorak42, @alxdavids: what do you think?

**Comment by dvorak42** [comment]
I'm not sure what baking the expiry into the tokens gives that can't be managed by rotating the issuer/verifier keys (or using public metadata (which is effectively the key used to sign))? That way issuers that care about more fine grained token expiration use the key rotation for that and issuers that only care about coarse token expiration use it for other metadata, allowing the protocol to treat both in the same way?

**Comment by chris-wood** [comment]
Yeah, I think the only two options are (a) rotate keys or (b) include the expiry information as public metadata (and need not be tied to the key used to sign). I'm not advocating for one or the other. 

> That way issuers that care about more fine grained token expiration use the key rotation for that and issuers that only care about coarse token expiration use it for other metadata, allowing the protocol to treat both in the same way?

Sure, that's reasonable. We should probably have text on this point. (That's partly why I filed this issue.)

**Comment by chris-wood** [comment]
We should also make sure to note that the validity window does narrow the anonymity set.
