### ISSUE TITLE
auth: suggestion about Token structure.

### ISSUE THREAD

**Issue by armfazh** [ietf-wg-privacypass/base-drafts#498]
Define `Token` structure based on the `AutenticationInput` struct.

In Section 2.2.1 and 2.2.3,
**Before:**
```c
struct {
    uint16_t token_type;
    uint8_t nonce[32];
    uint8_t challenge_digest[32];
    uint8_t token_key_id[Nid];
    uint8_t authenticator[Nk];
} Token;

struct {
    uint16_t token_type;
    uint8_t nonce[32];
    uint8_t challenge_digest[32];
    uint8_t token_key_id[Nid];
} AuthenticatorInput;
```

**After:**
```c
struct {
    uint16_t token_type;
    uint8_t nonce[32];
    uint8_t challenge_digest[32];
    uint8_t token_key_id[Nid];
} AuthenticatorInput;

struct {
    AuthenticatorInput authInput;
    uint8_t authenticator[Nk];
} Token;
```

**Comment by tfpauly** [comment]
While they do share that part, the authenticator input is really just covering the first parts of the token. From a naming perspective, switching this would be backwards to the meaning. The token is the main thing that matters, and the authenticator input is the derived structure.
