### ISSUE TITLE
Accommodating two round protocols

### ISSUE THREAD

**Issue by chris-wood** [ietf-wg-privacypass/base-drafts#50]
Some protocols, like [blind Schnorr signature schemes](https://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.3.6950&rep=rep1&type=pdf), require more than 1 round trip to complete. Currently, the protocol assumes a protocol that runs in one round trip, with some offline public key distribution step. In particular, issuance request messages are mapped almost directly to the underlying OPRF blind/request message. 

We should consider what needs to change, if anything, to accommodate these differently shaped protocols. I suggest we loosen the 1-1 restriction (?) from the Privacy Pass API to the underlying cryptographic protocol APIs. It just so happens that Privacy Pass maps nicely to the OPRF construction, but that need not be the case. For example, and hand waving over details, in the blind Schnorr case, an implementation of the issuance request flow could involve first fetching the nonce commitment from the server, and then sending a blinded value for evaluation. 

@dvorak42, what do you think?

**Comment by chris-wood** [comment]
@alxdavids what do you want to do here? Should we refactor the protocol to run in two rounds? Perhaps something like the following:

- CommitRequest
- CommitResponse
- IssueRequest
- IssueResponse

During the commitment flow (first round trip), the server can provide any sort of nonce or whatever is needed for the underlying protocol.

**Comment by alxdavids** [comment]
I think that sounds fine. Presumably in this architecture, the CommitRequest from the Client will mostly be an empty message (at least for 3-round protocols)?

**Comment by dvorak42** [comment]
For 1 round protocols, would the key commitment/configuration could be used to provide a 'default' result to the CommitResponse, either hardcoded as part of the version (or some parameter in the configuration)?

**Comment by chris-wood** [comment]
> For 1 round protocols, would the key commitment/configuration could be used to provide a 'default' result to the CommitResponse, either hardcoded as part of the version (or some parameter in the configuration)?

Not sure! We'd have to play with it and see what works.

**Comment by chris-wood** [comment]
@alxdavids will draft a PR based on the commit request/response flow, where the response includes some implementation-specific handle to state needed for the subsequent issuance flow. For one round protocols, the handle will be a fixed (empty?) string passed to the issuance flow.

**Comment by alxdavids** [comment]
I think this has been fixed by #62, @chris-wood to confirm?
