### ISSUE TITLE
Nit: Clarify responding to multiple token challenges

### ISSUE THREAD

**Issue by smhendrickson** [ietf-wg-privacypass/base-drafts#501]
[Section 2.1.2.1](https://www.ietf.org/archive/id/draft-ietf-privacypass-auth-scheme-14.html#name-sending-multiple-token-chal) indicates clearly that multiple challenges can be present, but is less clear on how a client is supposed to respond. I think it would be best to add a sentence indicating that the protocol expects clients to respond to exactly one challenge, if it chooses to respond:

```diff
...
If the origin has a preference for one challenge over another (for example, if one uses a token type that is faster to verify), it can sort it to be first in the list of challenges as a hint to the client.
+If clients choose to respond, clients should satisfy exactly one of the challenges presented.
```

I can raise this as a PR once agreement is reached.

**Comment by tfpauly** [comment]
Section 3.2 does cover this a bit:

https://ietf-wg-privacypass.github.io/base-drafts/draft-ietf-privacypass-auth-scheme.html#name-choosing-between-multiple-c

Do you think we need more there?

**Comment by smhendrickson** [comment]
Agreed this is a better home for the addition. I'll send a PR.
