### ISSUE TITLE
Accommodate client and server metadata 

### ISSUE THREAD

**Issue by chris-wood** [ietf-wg-privacypass/base-drafts#63]
The APIs currently do not allow clients or servers to supply metadata into the issuance flow. Absent a slot for metadata, how would one implement the PMB or the PrivateStats variants? One way would be to add client public metadata to the Generate API, and server public and private metadata to the Issue API, and communicate these in the requests and responses as needed. The instantiations/ciphersuites could then impose limits on these inputs as needed. For example, the PMB variant might limit the server private metadata to a single byte of value 0x00 or 0x01, and the public metadata would be empty. 

@dvorak42, would that be workable?

**Comment by dvorak42** [comment]
I'd guess it would be cleanest in the Issue API, especially for the private metadata variant, but seems like a reasonable way. The PrivateStats variant may need a bit more to support larger amounts of public metadata.

**Comment by chris-wood** [comment]
Cool. I'll prep a PR!

**Comment by chris-wood** [comment]
I think we can close this now that some issuance protocols admit public metadata.
