### ISSUE TITLE
Add redemption contexts

### ISSUE THREAD

**Issue by chris-wood** [ietf-wg-privacypass/base-drafts#66]
As discussed during IETF 110, the architecture document should provide guidance on how redemption contexts can be used and how they impact privacy. This is a bit of the calculus we don't yet have.

cc @dvorak42, @alxdavids

**Comment by dvorak42** [comment]
Yeah, this likely needs to be embedded both into the Architecture draft for the generic concept of a context, and then an actual instantiation of redemption contexts in the HTTP API doc.

**Comment by chris-wood** [comment]
Yep 👍 should we split out the HTTP work into a separate issue?
