### ISSUE TITLE
Refactoring the redemption flow

### ISSUE THREAD

**Issue by chris-wood** [ietf-wg-privacypass/base-drafts#67]
Currently, RedemptionRequest messages have the following structure:

```
struct {
  opaque data<1..2^16-1>; // input to the token issuance flow
  opaque tag<1..2^16-1>;  // output of the token issuance flow
  opaque info<1..2^16-1>; // application information bound to the token
} RedemptionRequest;
```

This has a couple of interesting properties. First, anyone with access to `data` can replay it in the issuance flow and compute `tag`. We might be able to address that by making the redemption flow a two round protocol, similar to what we've done for the issuance flow, or by allowing clients to encrypt `data` under the redeemer's public key. Or something else entirely.

Second, `tag` effectively authenticates `info`. Is there any reason why we couldn't merge these two fields and encrypt the latter with an AEAD? And if we were to do that, perhaps we could simplify the redemption interface and have it produce a secret that applications use as needed? Specifically, the `Redeem` function might return a secret rather than a `RedemptionRequest`. Turning the redemption API into an Export-like interface might help accommodate different application use cases.

cc @armfazh, @siyengar, @dvorak42

**Comment by siyengar** [comment]
I was actually thinking that since associating tag with info doesn't seem to solve a real problem, we could simplify this by just sending the token and unblinded voprf output without needing an info field to be involved in the first place.

**Comment by chris-wood** [comment]
> I was actually thinking that since associating tag with info doesn't seem to solve a real problem

This is the part I don't quite understand. The `tag` _is_ the VOPRF output. It's proof that the client previously went through the issuance flow with the server given input `data`. (The current draft's usage of the VOPRF API is out of date.)

**Comment by dvorak42** [comment]
Rather, the VOPRF spec has the output as a binding of the token itself with the unblinded token. I think to get the behavior you want here, the PrivacyPass spec should indicate that the input into the Redeem API can just be the empty string when not used, or just remove the info parameter complretely from Redeem and pass the empty string into the VOPRF Finalize API.

**Comment by chris-wood** [comment]
> I think to get the behavior you want here, the PrivacyPass spec should indicate that the input into the Redeem API can just be the empty string when not used, or just remove the info parameter complretely from Redeem and pass the empty string into the VOPRF Finalize API.

This seems to be the crux of the issue here: `info` is no longer present in the VOPRF Finalize API :-)

So we can probably drop it from Redeem, and have the token output be returned (as proposed above). This is separate from whether or not we need to account for replay attacks on the token `input` with two rounds or encryption, I think.

**Comment by siyengar** [comment]
Ya sorry the last statement was a bit confusing.

Ya I think you're right, getting rid of info should solve the problem. And then call it VOPRF_output rather than a tag.

It seems like these 2 apis are out of sync 

https://cfrg.github.io/draft-irtf-cfrg-voprf/draft-irtf-cfrg-voprf.html#name-finalize
Finalize(input, blind, evaluatedElement)

https://ietf-wg-privacypass.github.io/base-drafts/draft-ietf-privacypass-protocol.html#name-redeem-2
Finalize(token.data, token.issued, info)
